options:
  solr-version:
    type: string
    default: '5.2.1'
    description: Which version of Solr to install
  schema:
    type: string
    default: ''
    description: The Solr schema to upload to the Zookeeper cluster