#!/usr/bin/python

import setup
setup.pre_install()

from charmhelpers.core import hookenv


def install():
    hookenv.log('Installing solr')
    # add steps for installing dependencies and packages here
    # e.g.: from charmhelpers import fetch
    #       fetch.apt_install(fetch.filter_installed_packages(['nginx']))

    # https://archive.apache.org/dist/lucene/solr/4.10.4/solr-4.10.4.tgz

    packages = [ 'ntp',
                 'openjdk-7-jdk',
                 'supervisor'
               ]
    fetch.apt_install(fetch.filter_installed_packages(packages))

if __name__ == "__main__":
    install()
